name: Production Deployment

on:
  release:
    types: [published]

jobs:
  deploy_staging:
    name: Deploy Production
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ vars.ENV_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '21.7.3'

      - name: Install dependencies
        run: npm install

      - name: Lint and build code, then publish to Vercel
        run: >
          npx vercel
          --token ${{ secrets.VERCEL_TOKEN }}
          -n ${{ vars.VERCEL_PROJECT }}
          --yes
          --prod

      - name: Success
        run: echo "🚀  Deploy successful - BLAST OFF WOO! (woot woot) !!! 🐕 🐕 🐕 🚀 "